### ISSUE TITLE
Target JRE as part of artifact name

### ISSUE THREAD

**Issue by ppiotrow** [fthomas/scala-steward#1038]
In one of my projects I can see update of `"com.microsoft.sqlserver" % "mssql-jdbc"`
from `7.2.2.jre8` to `7.2.2.jre11`, where it should stay at `jre8`.
https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc

I also know such JRE versioning exist for other projects like Guava.
https://mvnrepository.com/artifact/com.google.guava/guava

Maybe this case could be handled by Steward?

**Comment by fthomas** [comment]
I think this version scheme is just wrong. A lot of tools compare version numbers to determine which of any two versions is newer. But if you add the something like the JRE to versions, comparing 7.2.2.jre8 to 7.2.2.jre11 is like comparing apples with oranges. If there are different artifacts for different JREs, this should be encoded in the artifact name and not in the version.

But there might be a way in Scala Steward to handle this situation without touching the version ordering code. One can configure via `.scala-steward.conf` which updates Scala Steward should allow or ignore. Maybe this can be tweaked a little bit to only allow updates of `"com.microsoft.sqlserver" % "mssql-jdbc"` if the version ends with `jre8`.

**Comment by ppiotrow** [comment]
I agree with the point that jre should be part of artifact name. This is actually the solution that scala chosen to append scala version 2.1{1,2,3} to the artifact id.
However companies like Microsoft or Google decided to publish it that way and more library designers will follow. Solution with `.scala-steward.conf` sounds not bad. Does it already support something more than just group&artifact id?

**Comment by exoego** [comment]
I think such configuration is not implemented yet and good to have.

Similar is happening in Scala world.
A sbt plugin scalajs-bundler published 0.15.0  for Scala.js 1.x & 0.15.0-0.6 for Scala.js 0.6.
This confused Scala Steward on my end.
https://github.com/scalacenter/scalajs-bundler/issues/311#issuecomment-522300820
For this case, one of maintainer said such suffix will be a part of artifactId in future version.

**Comment by fthomas** [comment]
`UpdatePattern`, which is used for `.scala-steward.conf`, allows to match versions but only via [`startsWith`](https://github.com/fthomas/scala-steward/blob/4c682207b6ddc60795d92a3a308420bf169010a0/modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala#L39). In this case we want to match a version if it ends with `jre8`. I would propose to change the version matching code to `endsWith` when `UpdatePattern.version` starts with `.*`.

Next we need to change [this code](https://github.com/fthomas/scala-steward/blob/4c682207b6ddc60795d92a3a308420bf169010a0/modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala#L33-L42) in `UpdatesConfig`. `isAllowed` should remove all versions from `update.newerVersions` if they don't match the version pattern. If none newer versions match that pattern it should return a `Left`, otherwise it should return a `Right` with an update that only contains matching newer versions.

`isIgnored` needs to be changed in a similar way but with the logic inverted (i.e. matching versions need to be removed from `update.newerVersions`).

The last ingredient is that we get more newer versions from sbt-updates (i.e. all newer `.jre8` and `.jre11` versions). This will happen with https://github.com/fthomas/scala-steward/pull/851. Even if that PR is not merged yet, we can still check in `FilterAlgTest` that the above changes work for an update with e.g. `newerVersions = Nel.of("7.2.2.jre11", "7.3.0.jre8", "7.3.0.jre11")` and a version pattern of `.*jre8`. Testing `FilterAlg.localFilter` should be sufficient for that.
