### ISSUE TITLE
Update build.sbt when upgrading sbt version

### ISSUE THREAD

**Issue by anilkumarmyla** [fthomas/scala-steward#1388]
Currently, updating sbt version is only reflected in file `project/build.properties`  but there might be usages of the same in `build.sbt` (sometimes as `crossSbtVersions`) which is not updated. 

Any reason for this? Ex: https://github.com/cb372/sbt-explicit-dependencies/pull/61 does not update the value in `build.sbt`

**Comment by mzuehlke** [comment]
As you mentioned `sbt` versions are currently only updated in files named `build.properties` see: https://github.com/fthomas/scala-steward/blob/master/modules/core/src/main/scala/org/scalasteward/core/io/package.scala#L31

It would be possible allow changes in "normal" source files to (as tested by `isGenericSourceFile`), but this could lead to too many changes. A problem that just happened with version numbers in text files (#1376).

Difficult decision.

**Comment by anilkumarmyla** [comment]
hmm, yeah. closing

**Comment by fthomas** [comment]
The file restriction is there since Scala Steward can update sbt versions (#665). I think we never tried updating sbt versions anywhere else.

If we allow Scala Steward to update sbt versions in other source files, it might produce a diff like https://github.com/cb372/sbt-explicit-dependencies/commit/014427ac6edc21d2e13e4cd7bf9133c05c8ded81 (including the change in the `.travis.yml`) or it might produce more bad PRs (as @mzuehlke pointed out). Maybe we should give it a try.
