### ISSUE TITLE
Wrong update of markdown file

### ISSUE THREAD

**Issue by alejandrohdezma** [fthomas/scala-steward#1394]
Since a couple of days ago `scala-steward` does not update my repositories properly. Instead of updating the version in `build.sbt` it changes the title of an old PR in the `CHANGELOG.md` file, as you can see in [this PR](https://github.com/alejandrohdezma/sbt-github/pull/153/files).

[![](https://user-images.githubusercontent.com/9027541/78821752-45da7e80-79da-11ea-859b-3e053d1d12f0.png)](https://github.com/alejandrohdezma/sbt-github/pull/153/files)

Other examples:

- https://github.com/alejandrohdezma/sbt-fix/pull/72
- https://github.com/alejandrohdezma/sbt-github/pull/123
- https://github.com/47degrees/memeid/pull/171

**Comment by fthomas** [comment]
Thanks for the report @alejandrohdezma! Other PRs that only updated Markdown files are:
* https://github.com/tmtsoftware/csw/pull/194
* https://github.com/typelevel/cats-tagless/pull/128
* https://github.com/RCMartins/blinky/pull/61
* https://github.com/erikvanoosten/metrics-scala/pull/241

Scala Steward updates Markdown files since https://github.com/fthomas/scala-steward/pull/1380. Although it works for some repositories, these examples make a good case for not modifying Markdown files by default. I think I'm going to revert #1380.

/cc @erikerlandson

**Comment by alejandrohdezma** [comment]
Great! Thank you!

Although that same functionality can be achieved by using `mdocVariables` from [Mdoc](https://scalameta.org/mdoc/docs/installation.html#sbt) like:

```sbt
//build.sbt

object V {

	//This will be the version updated by scala-steward
	val specs2 = "4.9.1"

}

//This will enable using `@specs2@` variable in your Markdown files
mdocVariables += "specs2" -> V.specs2
```
