### ISSUE TITLE
PRs with broken urls

### ISSUE THREAD

**Issue by kiranbayram** [fthomas/scala-steward#1403]
Hello there,

Today i saw a PR (repo is private so can't give a link) where urls were broken. So i was wondering if we can use `ExistenceClient` to check urls returned by `CoursierAlg.getArtifactIdUrlMapping` and either filter the ones with broken url out or show them as text (instead of link).

WDYT?

**Comment by mzuehlke** [comment]
Hello,

is the PR itself valid ? Because if the returned URL is broken the artefact itself maybe missing, too? I'm asking because this would mean that the root cause is within coursier. If we would just filter this, we would hide a problem.
If the result from cooursier is as expecte, I agree with you that we should only provide valid URLs in the PRs.

**Comment by kiranbayram** [comment]
PR itself is valid and artifacts are fine but the links are broken probably due to some incorrect configuration for the dependencies i guess. And I don't like having broken links in PR (whatever the reason may be)

**Comment by kiranbayram** [comment]
And i opened an issue for the case i encountered -> https://github.com/softwaremill/sttp/issues/505

**Comment by fthomas** [comment]
We're filtering URLs without scheme (#1171) and non-browsable URLs (#1071) so I guess it also makes sense to filter non-existing URLs, too.
