### ISSUE TITLE
Update only specified dependency (cli argument for updates.allow?)

### ISSUE THREAD

**Issue by MPV** [fthomas/scala-steward#1470]
## What

Could Scala Steward create pull-requests for only a specific dependency (across multiple downstream repositories)?

## Why?

If a dependency (in our case, an internal private library) is updated, we'd like to get create pull requests for this library (and only that) in downstream consumers of this library.

## What I've tried:

We use Scala Steward through the [scala-steward-action](https://github.com/scala-steward-org/scala-steward-action), so it would be helpful to be able to pass this as a CLI argument.

Just setting [`updates.allow` in .scala-steward.conf](https://github.com/fthomas/scala-steward/blob/master/docs/repo-specific-configuration.md) wouldn't help since Scala Steward checks out the repos itself, where I can't modify that file locally per runthrough.

## Notes

I understand that changing this would be a bit of a shift in which purpose Scala Steward fulfills, 
from: 
`update all dependencies in this/these repos` (consumer-centric)
into:
`update this dependency in all my consumers` (producer/dependency-centric)

Curious to hear your thoughts on this.

**Comment by fthomas** [comment]
@mzuehlke noted that #1483 could solve this issue and I agree with Marco that it looks like a nice solution for this request. What do you think, @MPV?

**Comment by MPV** [comment]
Looks great, thanks @mzuehlke & @fthomas!

**Comment by ches** [comment]
Part of our use case for #1483 is pretty much the same, it'd be good perhaps to give it as motivation on the PR but I'll echo it here as also a testimonial ☺️ 

We have a number of common libraries within the organization that are widely adopted. In order to help a small number of volunteer maintainers support them, Scala Steward keeps our little private ecosystem moving forward.

With downstream consumers that are application projects with large dependency graphs, though, the full firehose of Maven Central updates is too much churn and risk for most app teams to tolerate day-to-day. We're aiming to run an instance of Steward scoped to updating our blessed libraries, which is hopefully much easier to opt into and even mandate.

Steward can bring us a little closer to library upkeep benefits of a monorepo, without a monorepo.

**Comment by fthomas** [comment]
Thanks for sharing your motivation for #1483, @ches, that's very helpful!
