### ISSUE TITLE
Document how to integrate with scala projects that use Maven

### ISSUE THREAD

**Issue by blast-hardcheese** [fthomas/scala-steward#291]
scala-steward is capable of running in a project that uses maven for project definition by using https://github.com/sbt/sbt-pom-reader to start sbt and get dependencies. If this can't be done reliably, it may need to be opt-in on a project-by-project basis.

Once the dependencies are enumerated, applying a different set of heuristics to the sbt version replacements seems straightforward enough.

**Comment by fthomas** [comment]
@plokhotnyuk Yes, it currently ignores `.pom` files because it is not a source file as defined by [`isSourceFile`](https://github.com/fthomas/scala-steward/blob/c1e768970c7414754e9be653d7cc0dbdc7075c54/modules/core/src/main/scala/org/scalasteward/core/io/package.scala#L23-L28). If we include `.pom` files there Scala Steward should be able to update versions that are defined like this:
```
<scalatest.version>3.0.7</scalatest.version>
```
because the name of the artifact and the version are on the same line. Better support for Maven would require more code changes.

**Comment by plokhotnyuk** [comment]
Let it be yet another reason to switch their build configuration to sbt.

**Comment by stanislav-chetvertkov** [comment]
Opened a pr https://github.com/fthomas/scala-steward/pull/1193, the main idea is to introduce another implementation for SbtAlg trait (which was renamed into BuildSystemAlg) and abstract it away from SBT specific methods like SBT adding plugins; the maven implementation is supposed to call and parse the output of maven plugins, some feedback at this stage would be helpful

some things like scalafix support still need to be implemented
