### ISSUE TITLE
Automatic branch update and forced pushes can potentially flood CI

### ISSUE THREAD

**Issue by renatocaval** [fthomas/scala-steward#384]
As discussed here: https://github.com/playframework/playframework/pull/9159#issuecomment-479859679

We are facing an issue in which Travis is being flooded with new builds over and over. That happens because we have had a few PRs opened by @scala-steward and on each new merge on `master`, @scala-steward updates the branch and sends a new push. 

I personally don't think that this should be the default behaviour because it can potentially hijack CI for long periods. 

Maintainers have a few options to enforce this, for instance, they can configure branch protection which will force them to update the branch via GitHub or they can use something like Mergify that does it automatically and sequenced without triggering many builds at the same time.

So, ideally, either @scala-steward simply leave the responsibility to the project maintainers or over a flag in `.scala-steward.conf` to disable it.

**Comment by fthomas** [comment]
Btw, this is mainly done to resolve merge conflicts which easily happen with scala-steward's PR since version numbers tend to be defined relatively adjacent in build files.

If scala-steward could figure out if a PR has conflicts with the base branch we could update PRs only if there are conflicts. That sounds like a good compromise between keeping PRs automatically mergeable and not uneccessarily stressing CI systems.

**Comment by dwijnand** [comment]
https://developer.github.com/v3/git/#checking-mergeability-of-pull-requests

But I'm not sure if "mergeability" means pure git (i.e. has merge conflicts or not) or PR mergeability (requires review, etc).

**Comment by fthomas** [comment]
Thanks for the hint. Since this is just another GitHub call it would be straightforward to implement.

Another option might be just using Git as shown in https://stackoverflow.com/a/501461/460387. The benefit of just using Git is that it would also work if scala-steward is ported to Bitbucket or GitLab
