### ISSUE TITLE
Configurable use of merge rather than rebase/force-push

### ISSUE THREAD

**Issue by djspiewak** [fthomas/scala-steward#486]
It's not at all uncommon for a dependency update to require further work before merge. Generally we (at slamdata) would want to do this by basing on scala-steward's PR branch, making some changes, and pushing them. For larger updates, multiple people may be doing this independently and/or collaborating. Force pushing the branch breaks all of this.

I would love it if we could configure (presumably on a per-repo basis) the force push behavior, causing scala-steward to use merge rather than rebase.

**Comment by fthomas** [comment]
scala-steward resets and force pushes when it detects that the base branch has newer commits than the update branch. This is mainly done to resolve potential merge conflicts caused by other scala-steward PRs because version numbers tend to be defined adjacent in build files. It does this only as long as nobody else pushed to the update branch. As also mentioned in https://github.com/fthomas/scala-steward/issues/384#issuecomment-480529402, I'd like to change scala-steward to only reset PRs if there are merge conflicts instead of always when the base branch is newer.

**Comment by djspiewak** [comment]
The problem is that someone may *pull* from the update branch, merge it into their work, and then have further unpushed changes when this happens. scala-steward cannot in any way detect this, and so this kind of collaborative pulling needs to either be forbidden by team policy, or scala-steward cannot reset/force-push and instead must merge.

**Comment by fthomas** [comment]
Ok, I understand that scala-steward must not force-push to enable this workflow. But what is unclear to me is how it can automatically resolve merge conflicts if it should do this at all. Maybe merging with `--strategy-option=theirs` and then applying the update again would work. I need to experiment with that.

Btw, if you don't want scala-steward to keep PRs up-to-date with the base branch, this already possible via the config option `updatePullRequests = false` in `.scala-steward.conf`.

**Comment by djspiewak** [comment]
Ahhhhh. That might be a viable option. I'm okay with scala-steward not auto-updating things, though it's certainly a lot nicer if it does.

I think one strategy might be to try a regular `git merge`. If it applies cleanly, then push that. If it doesn't apply cleanly, then roll it back and try a `--strategy-option=theirs` and reapply as necessary.

**Comment by fthomas** [comment]
Merging with `--strategy-option=theirs` instead of resetting has been implemented in #757 and the first tests are quite convincing. (See for example: https://github.com/fthomas/refined-sjs-example/pull/15/commits.)

Together with #724 Scala Steward only updates a PR if there are merge conflicts and if there are merge conflicts it would merge the base branch with the strategy option `theirs` and apply the update again. I don't plan to make any of this configurable because I think the described behaviour is a very good default.
