### ISSUE TITLE
SBT Plugin not cleaned up after run

### ISSUE THREAD

**Issue by niij** [fthomas/scala-steward#855]
The `StewardPlugin.scala` plugin is not cleaned up after using scala-steward. The following 2 plugin files persist.

`/jenkins/.sbt/0.13/plugins/StewardPlugin.scala` and `/jenkins/.sbt/1.0/plugins/StewardPlugin.scala`

It seems they're being created here "temporarily" but never cleaned up. https://github.com/fthomas/scala-steward/blob/f251fcdaac80f55bc0fb21017268c8a77fe70be4/modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala#L71-L79

Thank you for  👀

**Comment by fthomas** [comment]
Thanks for the report, @niij. The files are created [here](https://github.com/fthomas/scala-steward/blob/a009c1f83e2752d83b3bfaad7c46adfb494d2fac/modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala#L60) but the code is not using `addGlobalPluginTemporarily` because that function was added later. I guess it makes sense to change `addGlobalPlugins` to use `addGlobalPluginTemporarily`.
