### ISSUE TITLE
Format on GroupID change

### ISSUE THREAD

**Issue by exoego** [fthomas/scala-steward#998]
Some repos uses Scalafmt and have strict CI rule that enforces format on every PRs.
Group ID change may cause bad format due to group id length change.

Maybe run scalafmt before commit?

**Comment by fthomas** [comment]
This mostly happens when code is aligned vertically. My feeling is that the gain is not worth the complexity and additional runtime this would introduce. I wish people would just stop using vertical alignment in their build files. :-) Another argument against vertical alignment is that it sometimes causes diffs that are bigger than they need to be ([here](https://github.com/typelevel/cats/pull/2323/files#diff-a84f91f20f040218bccd09fed4761fb3) is one example).

**Comment by exoego** [comment]
Agreed.
Closing since this is out of proportion to the benefit.
